var searchData=
[
  ['inference_20engine_3a_20tinychatengine_0',['LLM Inference Engine: TinyChatEngine',['../index.html#autotoc_md5',1,'']]],
  ['inference_20library_1',['TinyChatEngine: On-Device LLM Inference Library',['../index.html#autotoc_md0',1,'']]],
  ['int4_20weight_20reordering_2',['Device-specific int4 Weight Reordering',['../index.html#autotoc_md12',1,'']]],
  ['int4_5fthread_5fargs_3',['int4_thread_args',['../structint4__thread__args.html',1,'']]],
  ['int4llamaattention_4',['Int4llamaAttention',['../classInt4llamaAttention.html',1,'']]],
  ['int4llamaattention_5finput_5',['Int4llamaAttention_input',['../structInt4llamaAttention__input.html',1,'']]],
  ['int4llamaattention_5foutput_6',['Int4llamaAttention_output',['../structInt4llamaAttention__output.html',1,'']]],
  ['int4llamadecoder_7',['Int4llamaDecoder',['../classInt4llamaDecoder.html',1,'']]],
  ['int4llamadecoder_5finput_8',['Int4llamaDecoder_input',['../structInt4llamaDecoder__input.html',1,'']]],
  ['int4llamadecoder_5foutput_9',['Int4llamaDecoder_output',['../structInt4llamaDecoder__output.html',1,'']]],
  ['int4llamadecoderlayer_10',['Int4llamaDecoderLayer',['../classInt4llamaDecoderLayer.html',1,'']]],
  ['int4llamadecoderlayer_5finput_11',['Int4llamaDecoderLayer_input',['../structInt4llamaDecoderLayer__input.html',1,'']]],
  ['int4llamadecoderlayer_5foutput_12',['Int4llamaDecoderLayer_output',['../structInt4llamaDecoderLayer__output.html',1,'']]],
  ['int4llamaforcausallm_13',['Int4LlamaForCausalLM',['../classInt4LlamaForCausalLM.html',1,'']]],
  ['int4llamaforcausallm_5finput_14',['Int4LlamaForCausalLM_input',['../structInt4LlamaForCausalLM__input.html',1,'']]],
  ['int4llamaforcausallm_5foutput_15',['Int4LlamaForCausalLM_output',['../structInt4LlamaForCausalLM__output.html',1,'']]],
  ['int4optattention_16',['Int4OPTAttention',['../classInt4OPTAttention.html',1,'']]],
  ['int4optattention_5finput_17',['Int4OPTAttention_input',['../structInt4OPTAttention__input.html',1,'']]],
  ['int4optattention_5foutput_18',['Int4OPTAttention_output',['../structInt4OPTAttention__output.html',1,'']]],
  ['int4optdecoder_19',['Int4OPTDecoder',['../classInt4OPTDecoder.html',1,'']]],
  ['int4optdecoder_5finput_20',['Int4OPTDecoder_input',['../structInt4OPTDecoder__input.html',1,'']]],
  ['int4optdecoder_5foutput_21',['Int4OPTDecoder_output',['../structInt4OPTDecoder__output.html',1,'']]],
  ['int4optdecoderlayer_22',['Int4OPTDecoderLayer',['../classInt4OPTDecoderLayer.html',1,'']]],
  ['int4optdecoderlayer_5finput_23',['Int4OPTDecoderLayer_input',['../structInt4OPTDecoderLayer__input.html',1,'']]],
  ['int4optdecoderlayer_5foutput_24',['Int4OPTDecoderLayer_output',['../structInt4OPTDecoderLayer__output.html',1,'']]],
  ['int4optforcausallm_25',['Int4OPTForCausalLM',['../classInt4OPTForCausalLM.html',1,'']]],
  ['int4optforcausallm_5finput_26',['Int4OPTForCausalLM_input',['../structInt4OPTForCausalLM__input.html',1,'']]],
  ['int4optforcausallm_5foutput_27',['Int4OPTForCausalLM_output',['../structInt4OPTForCausalLM__output.html',1,'']]],
  ['int8optattention_28',['Int8OPTAttention',['../classInt8OPTAttention.html',1,'']]],
  ['int8optattention_5finput_29',['Int8OPTAttention_input',['../structInt8OPTAttention__input.html',1,'']]],
  ['int8optattention_5foutput_30',['Int8OPTAttention_output',['../structInt8OPTAttention__output.html',1,'']]],
  ['int8optdecoder_31',['Int8OPTDecoder',['../classInt8OPTDecoder.html',1,'']]],
  ['int8optdecoder_5finput_32',['Int8OPTDecoder_input',['../structInt8OPTDecoder__input.html',1,'']]],
  ['int8optdecoder_5foutput_33',['Int8OPTDecoder_output',['../structInt8OPTDecoder__output.html',1,'']]],
  ['int8optdecoderlayer_34',['Int8OPTDecoderLayer',['../classInt8OPTDecoderLayer.html',1,'']]],
  ['int8optdecoderlayer_5finput_35',['Int8OPTDecoderLayer_input',['../structInt8OPTDecoderLayer__input.html',1,'']]],
  ['int8optdecoderlayer_5foutput_36',['Int8OPTDecoderLayer_output',['../structInt8OPTDecoderLayer__output.html',1,'']]]
];
