var searchData=
[
  ['m1_202021_20_3a_0',['M1 2021 :',['../index.html#autotoc_md3',1,'LLaMA Chat Demo on an Apple MacBook Pro (M1, 2021):'],['../index.html#autotoc_md2',1,'VILA Demo on an Apple MacBook Pro (M1, 2021):']]],
  ['macbook_20pro_20m1_202021_20_3a_1',['MacBook Pro M1 2021 :',['../index.html#autotoc_md3',1,'LLaMA Chat Demo on an Apple MacBook Pro (M1, 2021):'],['../index.html#autotoc_md2',1,'VILA Demo on an Apple MacBook Pro (M1, 2021):']]],
  ['macos_2',['MacOS',['../index.html#autotoc_md9',1,'']]],
  ['matmul_5fparams_3',['matmul_params',['../structmatmul__params.html',1,'']]],
  ['matmuloperator_4',['MatmulOperator',['../classmatmul_1_1MatmulOperator.html',1,'matmul']]],
  ['matrix_5',['matrix',['../structmatrix.html',1,'']]],
  ['matrix3d_6',['Matrix3D',['../classMatrix3D.html',1,'']]],
  ['matrix3d_3c_20float_20_3e_7',['Matrix3D&lt; float &gt;',['../classMatrix3D.html',1,'']]],
  ['matrix3d_3c_20int_20_3e_8',['Matrix3D&lt; int &gt;',['../classMatrix3D.html',1,'']]],
  ['matrix3d_3c_20int8_5ft_20_3e_9',['Matrix3D&lt; int8_t &gt;',['../classMatrix3D.html',1,'']]],
  ['matrix3d_3c_20uint8_5ft_20_3e_10',['Matrix3D&lt; uint8_t &gt;',['../classMatrix3D.html',1,'']]],
  ['matrix4d_11',['Matrix4D',['../classMatrix4D.html',1,'']]],
  ['matrix4d_3c_20float_20_3e_12',['Matrix4D&lt; float &gt;',['../classMatrix4D.html',1,'']]],
  ['max_5ferror_5finfo_13',['max_error_info',['../structmax__error__info.html',1,'']]],
  ['metalmatmulbuffers_14',['MetalMatmulBuffers',['../structMetalMatmulBuffers.html',1,'']]],
  ['metalmatmulint4_15',['MetalMatmulInt4',['../classMetalMatmulInt4.html',1,'']]],
  ['metalmatmulint4imp_16',['MetalMatmulInt4IMP',['../classMetalMatmulInt4IMP.html',1,'']]],
  ['metalmatmulparams_17',['MetalMatMulParams',['../structMetalMatMulParams.html',1,'']]],
  ['model_20support_18',['Quantization and Model Support',['../index.html#autotoc_md16',1,'']]],
  ['model_20vlm_20chatbot_20with_20tinychatengine_19',['Deploy vision language model (VLM) chatbot with TinyChatEngine',['../index.html#autotoc_md14',1,'']]],
  ['model_20zoo_20',['Download and Deploy Models from our Model Zoo',['../index.html#autotoc_md18',1,'']]],
  ['model_5fconfig_21',['model_config',['../structmodel__config.html',1,'']]],
  ['models_20from_20our_20model_20zoo_22',['Download and Deploy Models from our Model Zoo',['../index.html#autotoc_md18',1,'']]]
];
